# Form implementation generated from reading ui file 'clientDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymongo 
myclient = pymongo.MongoClient("mongodb+srv://TraMy:Test123456789@moi.5pccgcl.mongodb.net/?retryWrites=true&w=majority&appName=Moi")
clientdb = myclient["users"]
clientcol = clientdb["userData"]

class Ui_MainWindow(object):
    def tt(self):
        print("userName: ", self.clientName.text())
        print("User password: ", self.clientPass.text())
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, -40, 641, 191))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 90, 641, 151))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.clientName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.clientName.setGeometry(QtCore.QRect(120, 40, 301, 22))
        self.clientName.setObjectName("clientName")
        self.clientPass = QtWidgets.QLineEdit(parent=self.groupBox)
        self.clientPass.setGeometry(QtCore.QRect(130, 90, 291, 22))
        self.clientPass.setObjectName("clientPass")
        self.chooseFile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chooseFile.setGeometry(QtCore.QRect(60, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chooseFile.setFont(font)
        self.chooseFile.setObjectName("chooseFile")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.successOrNot = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.successOrNot.setGeometry(QtCore.QRect(170, 330, 431, 22))
        self.successOrNot.setObjectName("successOrNot")
        self.fileName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fileName.setGeometry(QtCore.QRect(170, 260, 291, 21))
        self.fileName.setObjectName("fileName")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.chooseFile.clicked.connect(self.clickHandler)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "UPLOAD / DOWNLOAD FILES"))
        self.groupBox.setTitle(_translate("MainWindow", "USER INFORMATION:"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.chooseFile.setText(_translate("MainWindow", "ChooseFIle"))
        self.pushButton.setText(_translate("MainWindow", "Upload"))
        self.pushButton_2.setText(_translate("MainWindow", "Downlaod"))

    def clickHandler(self):
        dialog = QtWidgets.QFileDialog()
        dialog.exec()
        self.fileName = dialog.selectedFiles()
    
    
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
